README.md
getClient method doest not exist in exemple.
=> (fix) - replace getClient method by client

README.md
* Changed constant on line 60 - users constant was defined twice.
* Added example on how to find by ObjectId()
* Line 71 changed from aggregation to aggregate - aggregation function does not exist in source code - aggregate does.
* Fixed syntax on update functions (incorrectly wrapped - missing {})
=> More changes to README.md

README.md, test.ts, ts/collection.ts, ts/database.ts
Hi, I added generic type to the collection class for defining collection data interface
=> Added support for collection generic type

.github/workflows/ci.yml, .vscode/settings.json, Cargo.lock, Cargo.toml, README.md, deps.ts, mod.ts, test.deps.ts, ts/collection.ts, ts/database.ts, ts/result.ts, ts/util.ts
cc @manyuanrong 
~Waiting on https://github.com/manyuanrong/deno-plugin-prepare/pull/26~ Done
=> Update for Deno 1.4.0

EXAMPLES.md, README.md
I just wanted to check if you guys are ok with this kind documentation. If that's the case I will document all the functions. I am using it to teach at university.
=> Examples documentation

src/collection/collection.ts, src/collection/commands/aggregate.ts, src/collection/commands/find.ts, src/protocol/cursor.ts, src/types.ts, test.ts
=> Refactor 添加aggregate方法

src/types.ts, src/utils/uri.ts, tests/auth.test.ts, tests/utils/uri.test.ts
=> Refactor uri解析和测试

src/collection/collection.ts, tests/curd.test.ts
=> Refactor fix updateMany bug

src/collection/commands/find.ts, src/types.ts, tests/curd.test.ts
I add a field to FindOptions named sort, typed Document. Support sort feature by option in find function or by chain calling
=> Add sort feature and fix #111

README.md
=> Update example URL in README.md

src/auth/base.ts, src/auth/scram.ts, src/client.ts
make cnnect compatible with api 3.6 of the driver node. Cleaning code and improving the definition of the api auth. Small fixes
=> make cnnect compatible with api 3.6 of the driver node. Cleaning code and improving the definition of the api auth. Small fixes

README.md, src/protocol/protocol.ts, tests/cases/03_curd.ts
=> fix: multiple find

README.md
=> added-mongo-atlas-to-remote

src/client.ts, src/cluster.ts, src/database.ts, src/types.ts, src/utils/srv.ts, src/utils/uri.ts, tests/cases/00_uri.ts, tests/cases/05_srv.ts, tests/test.ts
- Resolve SRV urls to seedlist and connect options
- Move connection / protocol from to cluster.ts and discover primary node on connect
- Run all commands on primary for now
=> Resolve SRV urls

mod.ts
Fixes #199 
- add export of classes Database and Collection for better typing in projects using deno_mongo
=> added export of Database and Collection class

deps.ts, tests/test.deps.ts
=> chore: update dependencies

src/cluster.ts, src/protocol/message.ts, src/protocol/protocol.ts, src/utils/srv.ts, tests/cases/01_auth.ts
=> chore: use ES6 for...of instead of forEach

src/auth/scram.ts, src/client.ts, src/cluster.ts, src/collection/collection.ts, src/error.ts, src/protocol/protocol.ts
=> made info in MongoError class accessible

bson/bson.d.ts, src/collection/collection.ts, src/collection/commands/update.ts, src/utils/bson.ts
=> chore: remove Bson.ObjectID export

src/collection/collection.ts, src/database.ts, src/types.ts, tests/cases/03_curd.ts
Someone would help me to check if everything works?
Features:
- Improvements in the types of filters and inserts.
- Added query, update and pagination operators. 
Fixes: #237 #183
=> feat: document types improvements

src/database.ts
=> fix: unallowed argument in listCollections command: batchSize

src/collection/collection.ts
=> chore: deprecate collection.insert method

.github/workflows/ci.yml, deps.ts, mod.ts, src/collection/collection.ts, src/gridfs/bucket.ts, src/gridfs/indexes.ts, src/gridfs/upload.ts, src/types.ts, src/types/gridfs.ts, src/types/readWriteConcern.ts, tests/cases/06_gridfs.ts, tests/cases/99_cleanup.ts, tests/common.ts, tests/test.ts
Closes https://github.com/denodrivers/deno_mongo/issues/238
Tasks:
=> feat: Add GridFS Basic API

src/gridfs/bucket.ts, src/gridfs/indexes.ts, tests/cases/06_gridfs.ts
I found the code for gridfs has some promises without await. I made a small fix to add those awaits.
=> fix: add missing await in src/gridfs

src/client.ts, tests/cases/02_connect.ts
Resolve: https://github.com/denodrivers/deno_mongo/blob/6e16c02f2952b4df88d9bd6c5dd55eefacbe495e/src/client.ts#L60
=> test(02_connect): Add `runCommand` test

.github/workflows/ci.yml
=> feat: support mongodb v5

deps.ts, src/auth/scram.ts, tests/cases/01_auth.ts, tests/test.deps.ts
=> chore(deps): drop std/hash

src/collection/commands/find.ts, tests/cases/08_find_cursor.ts, tests/test.ts
=> fix: make options immutable

README.md, deps.ts, mod.ts, src/auth/base.ts, src/auth/scram.ts, src/auth/x509.ts, src/client.ts, src/collection/collection.ts, src/collection/commands/aggregate.ts, src/collection/commands/find.ts, src/collection/commands/update.ts, src/database.ts, src/gridfs/bucket.ts, src/gridfs/indexes.ts, src/gridfs/upload.ts, src/protocol/cursor.ts, src/protocol/handshake.ts, src/protocol/message.ts, src/protocol/protocol.ts, src/types.ts, src/types/gridfs.ts, tests/cases/import_worker.ts
This follows the Node.js Driver better
What do you think @erfanium ?
=> Proposal: Provide direct exports of Bson lib

README.md
Added Deno Rest boilerplate example showcasing deno_mongo usage
=> Adding example for Deno Rest boilerplate

src/client.ts, src/utils/srv.ts
Hi, 
just to clarify, this is not a PR to fix a typo that should look nice in my profile, this typo has been annoying me for three months now and I just realised that I can just go ahead and fix it myself :)
Thanks for the module.
Best regards,
Robin
=> fix typo in error message

src/types.ts
=> fix(types): Added typing for just pushing a single element
