README.md
mod.ts
test.ts
ts/util.ts

Internally call `await init()` when the module is loaded.
As suggested in #24.

Remove init from public api

---

ts/tests/types-check.test.ts
ts/types.ts

Update the regex used for id validation, so that it matches the **whole** string.
Add two more tests for invalid ids.
Fixes #28.

Fix ObjectId regex and add tests for invalid ids

---

README.md
mod.ts

@manyuanrong When you released v0.9.0 you did not update the version in `mod.ts`. deno_mongo was downloading the v0.8.0 plugin for v0.9.0. This PR bumps the version to v0.9.1. You just have to release this version with this PR to fix the issue.
Closes #78

Bump to v0.9.1

---

ts/type_convert.ts

Module was not supporting inserts and updates of `Map` instances. This pull requests enables the support of map parsing by converting each instance in a Javascript object using the `Object.fromEntries` function call

Support map conversion

---

README.md
ts/collection.ts
ts/types.ts

Hay there,
I have added the skip() and limit() feature which I found was missing while I was working on a project with **pagination support**.
```js
// Skip
const skipTwo = await users.skip(2).find();
// Limit
const featuredUser = await users.limit(5).find();
```
Expecting a positive review 👍

Added support for skip() and limit()

---

src/protocol/cursor.ts
tests/curd.test.ts

Empty cursors now yield nothing instead of a single `undefined` value.
Fixes #157

Fix empty cursor async iterators to not yield undefined

---

src/types.ts

It's a fix to solve type error as shows in issue #179, adding de property noCursorTimeout in FindOptions interface

Fix: add noCursorTimeout in FindOptions interface

---

src/cluster.ts

'hello' is not implemented for older mongos, should use isMaster instead. (https://jira.mongodb.org/browse/SERVER-49986)
Fixes https://github.com/denodrivers/deno_mongo/issues/200#issuecomment-846420784

fix: Use isMaster instead of hello to support older instances

---

src/collection/collection.ts

aggregate result type is not always the same as collection type. so an optional generic for this method is required

Fix: add a optional generic to collection aggregate type

---

src/collection/collection.ts
src/types.ts
tests/cases/04_indexes.ts

I need `dropIndexes` for my project so I took the opportunity to contribute to the driver.
However I'm not sure about the interface. Currently it's close to the [command](https://docs.mongodb.com/manual/reference/command/dropIndexes/) to be consistent with the current `createIndexes` method, but it's totally different from the interface provided by the nodejs driver where [dropIndex](http://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#dropIndex) can only drop indexes one at a time and where [dropIndexes](http://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#dropIndexes) drops all indexes.
Also I'm not sure about the type of the result of the command, I didn't find the documentation on this subject.

implement dropIndexes

---

src/collection/collection.ts
src/types.ts
tests/cases/03_curd.ts
tests/cases/99_cleanup.ts

I need the `findAndModify` operation for a project, so I figured I'd try and contribute it to the driver. 
This also adds a few interfaces to lock down the interface in terms of types, that could be re-used in other existing interfaces like `findOne`, although I didn't change those yet.

implement findAndModify

---

src/collection/collection.ts
tests/cases/03_curd.ts

feat: add `countDocuments` and `estimatedDocumentCount` methods and deprecate `count` method

---

src/client.ts
tests/cases/02_connect.ts

Expected behavior from https://mongodb.github.io/node-mongodb-native/3.1/api/MongoClient.html#db

fix(client): use connection db option as default database name

---

src/utils/uri.ts

The [Mongo connection string standard](https://docs.mongodb.com/manual/reference/connection-string/) states that, following the 
`mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]` format, 
> (...) the client will attempt to authenticate the user to the authSource. If authSource is unspecified, the client will attempt to authenticate the user to the defaultauthdb. And if the defaultauthdb is unspecified, to the admin database.
This PR implements auth from the authSource option, with greater priority than defaultauthdb, as stated above.

Add authentication using authSource

---

deps.ts
src/client.ts
src/cluster.ts
src/database.ts
tests/cases/01_auth.ts
tests/test.deps.ts

This PR removes the manual defaulting of the `options` parameter in various functions.
```typescript
// Previously, functions that took in an `options` object
// manually used `if` conditions for defaulting.
function someFunc(options?: Options) {
if (!options) options = {};
// ...
}
```
Now, we use ES6 default parameters.
```typescript
// Hooray!
function someFunc(options: Options = {}) {
// ...
}
```
I have also continued some work on my previous PR (#218) by removing the usage of `return await` in the `Cluster` class.
Finally, I also bumped up the `std` dependencies to `0.105.0` (the latest as of writing). One of the tests was broken as a result of the upgrade, but the fix was trivial. The test case in question asserted a value (`saltedPassword`) to be of type `number[]` rather than to …

Chore: assorted code clean-up and dependency bumps

---

src/client.ts
src/types.ts

Sometimes we need to access build info, such as version information to adjust the behavior of the driver.

feat: cache build info in connection

---

src/utils/uri.ts
tests/cases/00_uri.ts

Currently when authSource and dbName comes together, parse ignores `dbName` that is not expected

Fix: uri parser authSource and dbName bug

---

bson/bson.d.ts
bson/bson.ts
deps.ts
src/types/gridfs.ts

@Some-Dood removes vendored bson module in #283, but this change currently breaks CI, because type checking for bson module fails. so we have to add it again.
https://github.com/denodrivers/deno_mongo/runs/4155954213?check_suite_focus=true

fix: use vendored bson

---

src/cluster.ts

It is better practice to use the `.close()` method than the `Deno.close` API. This makes the code also work in Deno Deploy conincidentally.﻿

refactor: remove use of Deno.close

---

src/cluster.ts

certFile is deprecated in Deno. Now is caCerts.

Update cluster.ts, certFile is deprecated in Deno. Now is caCerts.

---

tests/cases/03_curd.ts
tests/cases/04_indexes.ts
tests/cases/99_cleanup.ts
tests/common.ts

We decided to write tests that do not depend on each other at https://github.com/denodrivers/deno_mongo/pull/302#issuecomment-983473822
- Use `insertOne` or `insertMany` for each test
- Run `await db.collection("mongo_test_users").drop().catch((e) => e);` for each test
- Use only `mongo_test_users` collection
- Delete `mongo_test_users_2` and `find_and_modify`

test(03_curd): Write tests that do not depend on each other

---

tests/cases/03_curd.ts
tests/cases/05_srv.ts
tests/test.deps.ts

Ref: https://deno.land/std@0.117.0/testing/README.md

chore: `assertThrowsAsync` is deprecated

---

src/types.ts

Attempt to fix issue #314 
I change the type info for $nin. When it's used on arrays, the type should be an array of the "array item"

fix: nin type when used on arrays

---

src/collection/commands/find.ts

This is what the Node mongodb driver does as far as I can tell. This is required for lower tier MongoDB Atlas instances.

fix: default `noCursorTimeout` to `false`

---

deps.ts
src/client.ts
src/cluster.ts
src/error.ts
src/gridfs/bucket.ts
src/protocol/protocol.ts
tests/test.deps.ts

chore(deps): remove std/testing dependency & bump

---

README.md

Hi everyone,
I have created a simple [module](https://deno.land/x/denomongo_unittest_utils@v0.4) to make unittesting with mocks for collections of this module. I think it would be beneficial to link this module in your readme. 
Thank you for your time in advance.
Best regards,
Robin

Proposal: Add Link to Module for Collection Mocking in readme

---

src/types.ts
tests/cases/03_curd.ts
tests/test.deps.ts

This is allowed, works, and is already being sent over, so it's really just a type thing.

Add `maxTimeMS` to FindOptions

---

README.md

The current step on how to connect to a local MongoDB instance can cause the error detailed in the following issue:
https://github.com/denodrivers/deno_mongo/issues/170
The proposed changes aim to fix that by replacing the "mongodb://localhost:27017" with "mongodb://127.0.0.1:27017".
This fixed was submitted by @michaeldesu in the issue linked above.

fix: how to connect to local MongoDB instance

---

src/database.ts
src/types.ts
tests/cases/03_curd.ts

This will simply add support for `createCollection` on `database` which resolves #352 
Since `createCollection` is just a special case of `runCommand`, I added some simple test cases only. 
- If some kind of validation is added in the future, it is likely that the query will be validated first at the driver level.
- `CreateCollectionOptions` can be expressed in more detail regarding options for capped collection, time series collection, validators and so on.

feat: support `database.createCollection`

---

src/gridfs/indexes.ts
tests/cases/06_gridfs.ts

IndexOptionsConflict for chunk collection - pr

---

src/types.ts
tests/cases/03_curd.ts

Extends $push, $pull and $pullAll types to include arrays nested within sub-documents.

update types to allow nested push, pull and pullAll

---

src/types.ts
tests/cases/03_curd.ts

Refactor the Filter type to only allow filter keys that exist on the document.
- Top-level keys as `{ filterKey: Value }`
- Nested keys as `{ "filter.key": Value }`
Arbitrary strings are no longer allowed.
Also includes a cleanup of the unused `Split` type I missed in the last PR (sorry!)
This PR  will probably break builds for people who have typos/non-existent keys in their code, but at least they would be aware of it.

Refactor Filter type to only allow valid keys

---

src/collection/collection.ts
tests/cases/03_curd.ts

According to [the Official document of mongoDB](https://www.mongodb.com/docs/manual/reference/method/db.collection.findAndModify/#return-data), findAndModify returns the document or **null**.
I test this problem by below code:
```ts
const collection = /*...*/;
const result = await collection.findAndModify(
{
name: 'abc',
},
{
update: {
$set: {
'someField': 12345,
},
},
new: false,
},
);
```
I've confirmed that the result is a pre-updated document if the document matches `{ name: 'abc' }` found, if not, the result is certainly null.
Maybe, the return type should be `Promise<T | null>`.
Last but not least, I apologize if there are any mistakes in my English writing. I am just Japanese student learning English ;)

findAndModify now returns T | null instead of T | undefined

---

README.md
src/collection/collection.ts
src/protocol/message.ts
src/types.ts

This PR fixes the return type from insert operations. If a type was specified in the provided schema `_id` field, it uses that type, else it returns an `ObjectId` type. Before this, it returned a union of the type and `ObjectId`

fix insert operation return types

---

src/database.ts

Closes #394
Added a few lines analogously to `mongoClient.runCommand` method.

feat: ability to run commands directly from DB instance

---

deps.ts
src/protocol/protocol.ts

instead of using the Deno.Reader and Deno.Writer apis, [which are going to be removed](https://docs.deno.com/runtime/manual/advanced/migrate_deprecations) in Deno 2.0, this PR moves towards using the ReadableStream and Writeable stream interfaces already available on the Deno.Conn interface. additionally, this removed the dependency on @std/io, which lightens the package a bit too
edit: not sure why tests are failing, they passed earlier when i was working on them locally

use modern deno streams

---

src/protocol/protocol.ts

if deserializeMessage throws for any reason (such as a BSONError), the pendingMessage promise will never resolve. this PR changes this behavior so that the promise will reject if there's an error thrown

fix: reject promise if deserializeMessage throws

---

deps.ts

this bumps the version of web_bson used to the latest one, fixing some weird issues i've ran into

chore: bump web_bson version
